/*
 * org.riverock.dbrevision - Database revision engine
 * For more information about DbRevision, please visit project site
 * http://www.riverock.org
 *
 * Copyright (C) 2006-2006, Riverock Software, All Rights Reserved.
 *
 * Riverock - The Open-source Java Development Community
 * http://www.riverock.org
 *
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.11.23 at 09:47:05 PM MSK 
//


package org.riverock.dbrevision.offline.config;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.riverock.generic.annotation.schema.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _WebmillConfig_QNAME = new QName("", "WebmillConfig");
    private final static QName _DateTimeSaving_QNAME = new QName("", "DateTimeSaving");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.riverock.generic.annotation.schema.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GenericConfigType }
     * 
     */
    public GenericConfigType createGenericConfigType() {
        return new GenericConfigType();
    }

    /**
     * Create an instance of {@link DatabaseConnectionType }
     * 
     */
    public DatabaseConnectionType createDatabaseConnectionType() {
        return new DatabaseConnectionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenericConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WebmillConfig")
    public JAXBElement<GenericConfigType> createWebmillConfig(GenericConfigType value) {
        return new JAXBElement<GenericConfigType>(_WebmillConfig_QNAME, GenericConfigType.class, null, value);
    }
}
