//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.14 at 03:36:49 PM MSK 
//


package org.riverock.dbrevision.annotation.schema.db;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DbSequenceReplacement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DbSequenceReplacement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TableWithIds" type="{http://dbrevision.sourceforge.net/xsd/dbrevision-structure.xsd}DbTable" minOccurs="0"/>
 *         &lt;element name="SequenceColumnName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ValueColumnName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isSkipAll" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DbSequenceReplacement", propOrder = {
    "tableWithIds",
    "sequenceColumnName",
    "valueColumnName"
})
public class DbSequenceReplacement {

    @XmlElement(name = "TableWithIds")
    protected DbTable tableWithIds;
    @XmlElement(name = "SequenceColumnName", required = true)
    protected String sequenceColumnName;
    @XmlElement(name = "ValueColumnName", required = true)
    protected String valueColumnName;
    @XmlAttribute
    protected Boolean isSkipAll;

    /**
     * Gets the value of the tableWithIds property.
     * 
     * @return
     *     possible object is
     *     {@link DbTable }
     *     
     */
    public DbTable getTableWithIds() {
        return tableWithIds;
    }

    /**
     * Sets the value of the tableWithIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbTable }
     *     
     */
    public void setTableWithIds(DbTable value) {
        this.tableWithIds = value;
    }

    /**
     * Gets the value of the sequenceColumnName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSequenceColumnName() {
        return sequenceColumnName;
    }

    /**
     * Sets the value of the sequenceColumnName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSequenceColumnName(String value) {
        this.sequenceColumnName = value;
    }

    /**
     * Gets the value of the valueColumnName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueColumnName() {
        return valueColumnName;
    }

    /**
     * Sets the value of the valueColumnName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueColumnName(String value) {
        this.valueColumnName = value;
    }

    /**
     * Gets the value of the isSkipAll property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsSkipAll() {
        return isSkipAll;
    }

    /**
     * Sets the value of the isSkipAll property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsSkipAll(Boolean value) {
        this.isSkipAll = value;
    }

}
