//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.30 at 03:53:10 PM MSD 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dbrevision.sourceforge.net/xsd/dbrevision-structure.xsd")
package org.riverock.dbrevision.annotation.schema.db;
