//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.30 at 03:53:10 PM MSD 
//


package org.riverock.dbrevision.annotation.schema.db;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PreviousName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{}Action"/>
 *           &lt;element ref="{}TableData"/>
 *           &lt;element name="Table" type="{http://dbrevision.sourceforge.net/xsd/dbrevision-structure.xsd}DbTable"/>
 *           &lt;element name="Sequence" type="{http://dbrevision.sourceforge.net/xsd/dbrevision-structure.xsd}DbSequence"/>
 *           &lt;element name="ImportedKey" type="{http://dbrevision.sourceforge.net/xsd/dbrevision-structure.xsd}DbImportedPKColumn"/>
 *           &lt;element name="PrimaryKey" type="{http://dbrevision.sourceforge.net/xsd/dbrevision-structure.xsd}DbPrimaryKey"/>
 *           &lt;element name="View" type="{http://dbrevision.sourceforge.net/xsd/dbrevision-structure.xsd}DbView"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "previousName",
    "actionOrTableDataOrTable"
})
@XmlRootElement(name = "Patch", namespace = "")
public class Patch {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "PreviousName")
    protected String previousName;
    @XmlElements({
        @XmlElement(name = "Sequence", type = DbSequence.class),
        @XmlElement(name = "View", type = DbView.class),
        @XmlElement(name = "Table", type = DbTable.class),
        @XmlElement(name = "PrimaryKey", type = DbPrimaryKey.class),
        @XmlElement(name = "ImportedKey", type = DbImportedPKColumn.class),
        @XmlElement(name = "Action", type = Action.class),
        @XmlElement(name = "TableData", type = TableData.class)
    })
    protected List<Object> actionOrTableDataOrTable;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the previousName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreviousName() {
        return previousName;
    }

    /**
     * Sets the value of the previousName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreviousName(String value) {
        this.previousName = value;
    }

    /**
     * Gets the value of the actionOrTableDataOrTable property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the actionOrTableDataOrTable property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActionOrTableDataOrTable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DbSequence }
     * {@link DbView }
     * {@link DbTable }
     * {@link DbPrimaryKey }
     * {@link DbImportedPKColumn }
     * {@link Action }
     * {@link TableData }
     * 
     * 
     */
    public List<Object> getActionOrTableDataOrTable() {
        if (actionOrTableDataOrTable == null) {
            actionOrTableDataOrTable = new ArrayList<Object>();
        }
        return this.actionOrTableDataOrTable;
    }

}
