//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.08 at 04:08:44 AM MSK 
//


package org.riverock.dbrevision.schema.db;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DbSequence complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DbSequence">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="min" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="max" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="inc" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="isCycle" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isOrder" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="cacheSize" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="lastNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DbSequence")
public class DbSequence {

    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute(required = true)
    protected int min;
    @XmlAttribute(required = true)
    protected String max;
    @XmlAttribute(required = true)
    protected int inc;
    @XmlAttribute
    protected Boolean isCycle;
    @XmlAttribute
    protected Boolean isOrder;
    @XmlAttribute
    protected Integer cacheSize;
    @XmlAttribute(required = true)
    protected long lastNumber;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the min property.
     * 
     */
    public int getMin() {
        return min;
    }

    /**
     * Sets the value of the min property.
     * 
     */
    public void setMin(int value) {
        this.min = value;
    }

    /**
     * Gets the value of the max property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMax() {
        return max;
    }

    /**
     * Sets the value of the max property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMax(String value) {
        this.max = value;
    }

    /**
     * Gets the value of the inc property.
     * 
     */
    public int getInc() {
        return inc;
    }

    /**
     * Sets the value of the inc property.
     * 
     */
    public void setInc(int value) {
        this.inc = value;
    }

    /**
     * Gets the value of the isCycle property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsCycle() {
        return isCycle;
    }

    /**
     * Sets the value of the isCycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCycle(Boolean value) {
        this.isCycle = value;
    }

    /**
     * Gets the value of the isOrder property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsOrder() {
        return isOrder;
    }

    /**
     * Sets the value of the isOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsOrder(Boolean value) {
        this.isOrder = value;
    }

    /**
     * Gets the value of the cacheSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCacheSize() {
        return cacheSize;
    }

    /**
     * Sets the value of the cacheSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCacheSize(Integer value) {
        this.cacheSize = value;
    }

    /**
     * Gets the value of the lastNumber property.
     * 
     */
    public long getLastNumber() {
        return lastNumber;
    }

    /**
     * Sets the value of the lastNumber property.
     * 
     */
    public void setLastNumber(long value) {
        this.lastNumber = value;
    }

}
