//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.08 at 04:08:44 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dbrevision.sourceforge.net/xsd/dbrevision-structure-3.0.xsd")
package org.riverock.dbrevision.schema.db;
