//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.06 at 08:17:38 PM MSD 
//


package org.riverock.dbrevision.annotation.schema.db;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.riverock.dbrevision.annotation.schema.db package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SchemaElement_QNAME = new QName("http://dbrevision.sourceforge.net/xsd/dbrevision-structure.xsd", "SchemaElement");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.riverock.dbrevision.annotation.schema.db
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DbDatabase }
     * 
     */
    public DbDatabase createDbDatabase() {
        return new DbDatabase();
    }

    /**
     * Create an instance of {@link SqlAction }
     * 
     */
    public SqlAction createSqlAction() {
        return new SqlAction();
    }

    /**
     * Create an instance of {@link DbSequence }
     * 
     */
    public DbSequence createDbSequence() {
        return new DbSequence();
    }

    /**
     * Create an instance of {@link RecordData }
     * 
     */
    public RecordData createRecordData() {
        return new RecordData();
    }

    /**
     * Create an instance of {@link DbField }
     * 
     */
    public DbField createDbField() {
        return new DbField();
    }

    /**
     * Create an instance of {@link DbDataSchema }
     * 
     */
    public DbDataSchema createDbDataSchema() {
        return new DbDataSchema();
    }

    /**
     * Create an instance of {@link Validator }
     * 
     */
    public Validator createValidator() {
        return new Validator();
    }

    /**
     * Create an instance of {@link DbIndexColumn }
     * 
     */
    public DbIndexColumn createDbIndexColumn() {
        return new DbIndexColumn();
    }

    /**
     * Create an instance of {@link ActionParameter }
     * 
     */
    public ActionParameter createActionParameter() {
        return new ActionParameter();
    }

    /**
     * Create an instance of {@link DbForeignKeyColumn }
     * 
     */
    public DbForeignKeyColumn createDbForeignKeyColumn() {
        return new DbForeignKeyColumn();
    }

    /**
     * Create an instance of {@link DbPrimaryKeyColumn }
     * 
     */
    public DbPrimaryKeyColumn createDbPrimaryKeyColumn() {
        return new DbPrimaryKeyColumn();
    }

    /**
     * Create an instance of {@link DbRevision.Module.Versions }
     * 
     */
    public DbRevision.Module.Versions createDbRevisionModuleVersions() {
        return new DbRevision.Module.Versions();
    }

    /**
     * Create an instance of {@link Patches }
     * 
     */
    public Patches createPatches() {
        return new Patches();
    }

    /**
     * Create an instance of {@link Patch }
     * 
     */
    public Patch createPatch() {
        return new Patch();
    }

    /**
     * Create an instance of {@link Action }
     * 
     */
    public Action createAction() {
        return new Action();
    }

    /**
     * Create an instance of {@link DbRevision }
     * 
     */
    public DbRevision createDbRevision() {
        return new DbRevision();
    }

    /**
     * Create an instance of {@link DbTable }
     * 
     */
    public DbTable createDbTable() {
        return new DbTable();
    }

    /**
     * Create an instance of {@link DbSchema }
     * 
     */
    public DbSchema createDbSchema() {
        return new DbSchema();
    }

    /**
     * Create an instance of {@link AddTableFieldAction }
     * 
     */
    public AddTableFieldAction createAddTableFieldAction() {
        return new AddTableFieldAction();
    }

    /**
     * Create an instance of {@link DbRevision.Module }
     * 
     */
    public DbRevision.Module createDbRevisionModule() {
        return new DbRevision.Module();
    }

    /**
     * Create an instance of {@link TableData }
     * 
     */
    public TableData createTableData() {
        return new TableData();
    }

    /**
     * Create an instance of {@link DbDataFieldData }
     * 
     */
    public DbDataFieldData createDbDataFieldData() {
        return new DbDataFieldData();
    }

    /**
     * Create an instance of {@link FieldData }
     * 
     */
    public FieldData createFieldData() {
        return new FieldData();
    }

    /**
     * Create an instance of {@link DbKeyActionRule }
     * 
     */
    public DbKeyActionRule createDbKeyActionRule() {
        return new DbKeyActionRule();
    }

    /**
     * Create an instance of {@link DbDataTable }
     * 
     */
    public DbDataTable createDbDataTable() {
        return new DbDataTable();
    }

    /**
     * Create an instance of {@link DbDataRecord }
     * 
     */
    public DbDataRecord createDbDataRecord() {
        return new DbDataRecord();
    }

    /**
     * Create an instance of {@link DbIndex }
     * 
     */
    public DbIndex createDbIndex() {
        return new DbIndex();
    }

    /**
     * Create an instance of {@link CustomClassAction }
     * 
     */
    public CustomClassAction createCustomClassAction() {
        return new CustomClassAction();
    }

    /**
     * Create an instance of {@link DbPrimaryKey }
     * 
     */
    public DbPrimaryKey createDbPrimaryKey() {
        return new DbPrimaryKey();
    }

    /**
     * Create an instance of {@link DbView }
     * 
     */
    public DbView createDbView() {
        return new DbView();
    }

    /**
     * Create an instance of {@link DbForeignKey }
     * 
     */
    public DbForeignKey createDbForeignKey() {
        return new DbForeignKey();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DbSchema }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dbrevision.sourceforge.net/xsd/dbrevision-structure.xsd", name = "SchemaElement")
    public JAXBElement<DbSchema> createSchemaElement(DbSchema value) {
        return new JAXBElement<DbSchema>(_SchemaElement_QNAME, DbSchema.class, null, value);
    }

}
