//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.27 at 04:14:20 PM MSD 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://generic.riverock.org/xsd/riverock-database-structure.xsd")
package org.riverock.dbrevision.annotation.schema.db;
