//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.08 at 04:08:44 AM MSK 
//


package org.riverock.dbrevision.schema.db.v3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DbForeignKeyColumn complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DbForeignKeyColumn">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="pkCol" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fkCol" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="seq" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DbForeignKeyColumn")
public class DbForeignKeyColumn {

    @XmlAttribute
    protected String pkCol;
    @XmlAttribute
    protected String fkCol;
    @XmlAttribute
    protected Integer seq;

    /**
     * Gets the value of the pkCol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkCol() {
        return pkCol;
    }

    /**
     * Sets the value of the pkCol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkCol(String value) {
        this.pkCol = value;
    }

    /**
     * Gets the value of the fkCol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFkCol() {
        return fkCol;
    }

    /**
     * Sets the value of the fkCol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFkCol(String value) {
        this.fkCol = value;
    }

    /**
     * Gets the value of the seq property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * Sets the value of the seq property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSeq(Integer value) {
        this.seq = value;
    }

}
